version: '3.3'

services:
  mysql:
    container_name: mysql-example
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: example@123